# Numpy

1. Numpy stands for numerical python
2. Numpy is used to perform advanced numerical computations on large datasets
3. Numpy can perform complex operations with less lines of code
4. It provides a very useful datastructure called array

syntax
import numpy

check version of numpy
np.__version__

Documentation available at numpy.org

In [2]:
import numpy as np

np.__version__

'1.24.2'

# Array
- Array is the collection of homohenous(same type) elements.

# np.array
Creation of array use np.array

In [5]:
lst = [10,20,30,40,50]
arr = np.array(lst)
print(arr, type(arr))

[10 20 30 40 50] <class 'numpy.ndarray'>


# List vs array
- With list we have to apply loop to perform element by elemnt operation.
    with array we can easily perform some operation rather than list
- A list has to store a lot of information for each element seperately bacause each element behaves differently in a list(heterogenous elments). Array is a collection of homogenous elements, so no need to manage elements individually.
- Arrays are faster than list

In [7]:
#Multiply each element of following list by 5

#List approach
lst=[10,20,30,40,50,60]
print(lst, type(lst))
for i in range(len(lst)):
    lst[i]*=5
print(lst)

[10, 20, 30, 40, 50, 60] <class 'list'>
[50, 100, 150, 200, 250, 300]


In [8]:
#Array approach
lst=[10,20,30,40,50,60]
arr = np.array(lst)
arr*5

array([ 50, 100, 150, 200, 250, 300])

# Why are array faster than list
- On list we have to use loops to perform some operation. Loops make the process slow
- Array's use vectorised operations by using array broadcasting and this process is much faster than loops.
- A list is a caoolection of heterogenous elements, whereas array is a collection of homogenous elements.

# Array upcasting
When we pass heterogenous elements to an array, it converts them to one type. This process is known as array upcasting

Array upcasting is using below hierarchy while upasting as below:
int -> float -> complex -> string -> object

In [10]:
arr = np.array([10,20,30,40,50])
arr.dtype

dtype('int64')

In [11]:
arr = np.array([10,20,30,40,50.0])
arr.dtype

dtype('float64')

In [15]:
arr = np.array([10,20+5j,30,40.7,50])
print(arr.dtype)
print(arr)

complex128
[10. +0.j 20. +5.j 30. +0.j 40.7+0.j 50. +0.j]


In [18]:
# In numpy, string are not available. It is represented by u representation. u=unicode
arr = np.array([10.5,20+5j,30,40.7,'50'])
print(arr.dtype)
print(arr)

<U64
['10.5' '(20+5j)' '30' '40.7' '50']


In [21]:
#When using derived datatype, compiler throws an array, to supress this defing dtype=object
arr = np.array([10.5,20+5j,30,[40.7,60.1],'50'])
print(arr.dtype)
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [22]:
arr = np.array([10.5,20+5j,30,[40.7,60.1],'50'], dtype=object)
print(arr.dtype)
print(arr)

object
[10.5 (20+5j) 30 list([40.7, 60.1]) '50']


In [24]:
arr = np.array([10.5,20+5j,30,40.7,60,'50',None, True])
print(arr.dtype)
print(arr)

object
[10.5 (20+5j) 30 40.7 60 '50' None True]


# Attributes on arrays

- dtype: Returns type of the elements an array contains
- size: Returns the number of elements an array contains
- shape: Returns a tuple. If tuple has single elements it represents number of elements
        If tuple has two elements, then first element is number of rows and second is number of columns.
- ndim : Returns the dimention of the array. 1d is called a vector

In [31]:
arr = np.array([10,20,30,40,50])
print(arr.dtype)
print(arr.size)
print(arr.shape)
print(arr.ndim)

int64
5
(5,)
1


In [33]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)

(2, 3)
2


# Creating different types of arrays

1. np.arange()
syntax: np.arrange(start, stop, step)

2. np.linspace()
Used to create an array of equally spaced values within a range of values
Difference between any two consequtive values is same across the elements of array 
syntax: np.linspace(start, stop, number of values)

3. np.zeros()
Returns an array of given shape where all elements of array is zero. The dimention of array needs to be passed in a tuple

4. np.ones()
Returns an array of given shape where all elements of array is one.

In [37]:
#Create a array that has the number 1 to 10
lst=[i for i in range(1,10)]
print(np.array(lst))

print(np.arange(1,11))

#Create a array of even numbers frpm 2 to 20
print(np.arange(2,21,2))

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [41]:
# np.linspace()
#Create  an array of 5 equally spaced values between 1 and 3

print(np.linspace(1,3,5))

print(np.linspace(1,10,20))

[1.  1.5 2.  2.5 3. ]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [43]:
#Create a 3X3 matrix where all elements are 0
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
x= np.ones((3,3), dtype=int)
print(x.dtype)
print(x)

int64
[[1 1 1]
 [1 1 1]
 [1 1 1]]
