In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('/Users/pawankumarkc/Documents/vscodepython/NLP/train_data/Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing data
Using simple imputer class, we can fill missing data with strategies(mean, median, most_frequent, constant)
Replace missing salary info. with average of all salaries

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 1:3]=imputer.fit_transform(X[:,1:3]) #We want to fill csv idex 1,2 but we specify 1:3 as this class eliminates the upper bound
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding Categorical data (1. Independent variable: X)
Using One hot encoding, we will categorise country column to different classes. Instead of working with string countries, we will encode them to 0's & 1's 
Purchased column has Yes/No, which will be replaced with 
transformers=[('encoder', OneHotEncoder, [0])]
Explain: transformer option takes 3 params, type of transformation='encoding' within quotes. Class ref. being used for transformation, and the index to be transformed. ie[0]. 
remainder='passthrough', means remaining columns will be pass throughed as transformation is not required there.

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding Categorical data (2. Dependent variable:y )
for encoding dependent variable (y)(In this case yes/no data), we use LabelEncoder class

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

Feature Scaling: Needs to be perfomred in order to avoid feature domination. This step is required for some ML Algorithms, not all.
Standardization and Normalization: Standardization is most commonly used over other.
Feature scaling is applied after spiltting of data into test and train and will not applied on test data
Feature scaling need not to be applied on dummy vaiables/features

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:]) #Only transform will be applied to test set as fitting should not be applied
#because X_test will be the input of the predict function

In [13]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [14]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
